In [7]:
import os
import pandas as pd

In [8]:
ROOT_DIR = os.path.dirname(os.getcwd())

ROOT_DIR

'C:\\Users\\matheus.carneiro\\Projetos\\gym-auto-planner'

In [9]:
df_raw = pd.read_csv(os.path.join(ROOT_DIR, 'datasets', 'gym_exercise_dataset.csv'))

df_raw.head()

,Exercise Name,Equipment,Variation,Utility,Mechanics,Force,Preparation,Execution,Target_Muscles,Synergist_Muscles,Stabilizer_Muscles,Antagonist_Muscles,Dynamic_Stabilizer_Muscles,Main_muscle,Difficulty (1-5),Secondary Muscles,parent_id
0,Neck Flexion,Cable,No,Basic or Auxiliary,Isolated,Pull,Sit on bench facing away from middle pulley. P...,Move head away from pulley by bending neck for...,"Sternocleidomastoid,","None,","Rectus Abdominis, Obliques,",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
1,Neck Flexion,Lever (plate loaded),No,Basic or Auxiliary,Isolated,Pull,Sit on seat in machine. Position padded lever ...,Move head forward by flexing neck until chin t...,"Sternocleidomastoid,","None,","Latissimus Dorsi, Deltoid, Posterior, Rhomboid...",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
2,Lateral Neck Flexion,Lever (plate loaded),No,Auxiliary,Isolated,Pull,Sit on seat in machine with feet apart . Pos...,Move head down to side by laterally flexing ne...,"Sternocleidomastoid,","Splenius, Erector Spinae, Levator Scapulae, Tr...","Latissimus Dorsi, Pectoralis Major, Sternal, P...",NaN,NaN,Neck,2,"Sternocleidomastoid, Levator Scapulae",NaN
3,Neck Flexion,Lever (selectorized),No,Basic or Auxiliary,Isolated,Pull,Sit on seat in machine. Position padded lever ...,Move head forward by flexing neck until chin t...,"Sternocleidomastoid,","None,","Latissimus Dorsi, Deltoid, Posterior, Rhomboid...",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
4,Lateral Neck Flexion,Lever (selectorized),No,Auxiliary,Isolated,Pull,Sit on seat in machine with feet apart. Positi...,Move head down to side by laterally flexing ne...,"Sternocleidomastoid,","Splenius, Erector Spinae, Levator Scapulae, Tr...","Latissimus Dorsi, Pectoralis Major, Sternal, P...",NaN,NaN,Neck,2,"Sternocleidomastoid, Levator Scapulae",NaN

In [10]:
muscle_groups = df_raw[['Target_Muscles', 'Secondary Muscles']]

muscle_groups.head()

         Target_Muscles                      Secondary Muscles
0  Sternocleidomastoid,                    Sternocleidomastoid
1  Sternocleidomastoid,                    Sternocleidomastoid
2  Sternocleidomastoid,  Sternocleidomastoid, Levator Scapulae
3  Sternocleidomastoid,                    Sternocleidomastoid
4  Sternocleidomastoid,  Sternocleidomastoid, Levator Scapulae

In [11]:
muscle_groups['full_set'] = muscle_groups.apply(
    lambda x: x['Target_Muscles'] + (x['Secondary Muscles'] if isinstance(x['Secondary Muscles'], str) else ''),
    axis=1)

muscle_groups.head()

,Target_Muscles,Secondary Muscles,full_set
0,"Sternocleidomastoid,",Sternocleidomastoid,"Sternocleidomastoid,Sternocleidomastoid"
1,"Sternocleidomastoid,",Sternocleidomastoid,"Sternocleidomastoid,Sternocleidomastoid"
2,"Sternocleidomastoid,","Sternocleidomastoid, Levator Scapulae","Sternocleidomastoid,Sternocleidomastoid, Levat..."
3,"Sternocleidomastoid,",Sternocleidomastoid,"Sternocleidomastoid,Sternocleidomastoid"
4,"Sternocleidomastoid,","Sternocleidomastoid, Levator Scapulae","Sternocleidomastoid,Sternocleidomastoid, Levat..."

In [12]:
list_muscles = [group.split(',') for group in muscle_groups['full_set'].tolist()]

list_muscles = [muscle.strip() for group in list_muscles for muscle in group]

set(list_muscles)

{'',
 'Adductors',
 'Anterior Deltoid',
 'Biceps Brachii',
 'Brachialis',
 'Brachioradialis',
 'Erector Spinae',
 'Gastrocnemius',
 'Gluteus Maximus',
 'Gluteus MaximusErector Spinae',
 'Hamstrings',
 'HamstringsHamstrings',
 'Hip Abductors',
 'Hip Adductors',
 'Hip Flexors',
 'Hip FlexorsHip Flexors',
 'Hip FlexorsIliopsoas',
 'Hip FlexorsObliques',
 'Hip FlexorsRectus Abdominis',
 'Infraspinatus',
 'Lateral Deltoid',
 'Latissimus Dorsi',
 'Levator Scapulae',
 'Lower Trapezius',
 'Middle Trapezius',
 'Obliques',
 'Pectoralis Major Clavicular',
 'Pectoralis Major Sternal',
 'Pectoralis Major SternalTriceps Brachii',
 'Pectoralis Minor',
 'Posterior Deltoid',
 'Pronators',
 'Quadratus Lumborum',
 'Quadriceps',
 'Rectus Abdominis',
 'Rhomboids',
 'Serratus Anterior',
 'Soleus',
 'Splenius',
 'Sternocleidomastoid',
 'Subscapularis',
 'Supinator',
 'Supraspinatus',
 'Teres Major',
 'Teres Minor',
 'Tibialis Anterior',
 'Trapezius',
 'Triceps Brachii',
 'Upper Trapezius',
 'Wrist Extensors',
 'Wrist Flexors'}

In [18]:
muscle_groups['target_count'] = muscle_groups.apply(lambda x: len([m for m in x['Target_Muscles'].split(',') if len(m.strip()) > 0]), axis=1)

muscle_groups[muscle_groups['target_count'] > 1]

,Target_Muscles,Secondary Muscles,full_set,target_count
166,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
167,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
168,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
169,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
170,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
...,...,...,...,...
253,"Infraspinatus, Teres Minor,","Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2
254,"Infraspinatus, Teres Minor,","Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2
255,"Infraspinatus, Teres Minor,","Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2
256,"Infraspinatus, Teres Minor,","Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2
257,"Infraspinatus, Teres Minor,","Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2

In [33]:
df_raw['Equipment'].apply(lambda x: ' '.join(x.split()).replace('\u200b','')).drop_duplicates().to_list()

['Cable',
 'Lever (plate loaded)',
 'Lever (selectorized)',
 'Weighted',
 'Body Weight',
 'Suspended',
 'Band Resistive',
 'Isometric',
 'Barbell',
 'Dumbbell',
 'Sled',
 'Smith',
 'Assisted',
 'Band-assisted',
 'Self-assisted',
 'Sled (selectorized)',
 'Sled (plate loaded)',
 'Assisted (machine)',
 'Assisted (partner)',
 'Suspension',
 'Plyometric',
 'Assisted Chest Dip',
 'Cable Standing Fly',
 'Lever (selectorized) Chest Dip',
 'Weighted Chest Dip',
 'Cable (pull side)',
 'Lever']